-- Insert reviews linking to product IDs (1-5 above)
INSERT INTO reviews (product_id, name, rating, title, body, verified, date) VALUES
(1, 'Ravi M.', 5, 'Unmatched intensity', 'This is not a casual fragrance. It announces you. The oud is authentic and deep, not synthetic. I get compliments every time I wear it. The longevity is remarkable—over 12 hours on my skin. Worth every rupee.', true, '2025-11-12'),
(1, 'Arjun K.', 4, 'Bold and refined', 'Excellent quality with a luxurious feel. The leather note is very present, and the overall composition feels like something from a Parisian atelier. I found it slightly heavy for daytime, but perfect for evenings.', true, '2025-10-28'),
(1, 'Nisha P.', 5, 'A masterpiece', 'Bought for my husband and he refuses to wear anything else. The balance between darkness and elegance is perfect. The bottle itself is art.', true, '2025-09-15'),
(2, 'Priya R.', 5, 'Absolutely divine', 'This scent is like walking through a rose garden at dawn. The saffron adds warmth without being heavy, and the dry down is pure silk. I have been wearing it daily for three months and still find new layers.', true, '2025-12-01'),
(2, 'Anjali D.', 4, 'Elegant and long-lasting', 'Beautiful fragrance with excellent projection. The white musk base is incredibly clean and modern. Would recommend to anyone looking for a signature scent.', true, '2025-11-20'),
(2, 'Meera T.', 5, 'The best rose I have tried', 'Not powdery, not sweet—just pure, luminous rose. The packaging is beautiful and the bottle is heavy with quality glass. I have already purchased two more bottles.', true, '2025-10-05'),
(3, 'Kunal V.', 5, 'Fresh without being generic', 'Most fresh fragrances feel like soap. Silver Meridian feels like sea air and cool cedar. Perfect for office wear and summer evenings.', true, '2025-11-30'),
(3, 'Shweta B.', 4, 'Clean and modern', 'A great unisex option. I share it with my partner and it suits both of us. The projection is moderate, making it intimate and appropriate for close settings.', true, '2025-09-22'),
(4, 'Rohit S.', 5, 'Warm and captivating', 'Golden Hour is the perfect gift. The amber is not cloying, the jasmine is bright, and the overall dry down feels like a warm embrace. My partner wears it and I can always smell her presence.', true, '2025-11-18'),
(4, 'Neha C.', 5, 'Luxury in a bottle', 'The bottle design is elegant, the scent profile is unique, and the value is exceptional compared to designer alternatives. Highly recommend.', true, '2025-08-30'),
(5, 'Vikram J.', 4, 'Bold and characterful', 'Strong and distinctive. The coffee note is surprising but adds depth. Not for the faint of heart, but if you want presence, this delivers. The packaging is premium and the gift box is beautiful.', true, '2025-11-05'),
(5, 'Ankit R.', 5, 'A new favorite', 'This is the kind of scent that becomes part of your identity. I have worn it for two months and friends ask about it constantly. The myrrh base is beautifully done.', true, '2025-10-14');
